src/sass/base/_base-components.scss
=> current page animation fix

src/partrials/header.html, src/sass/components/_spinner.scss, src/sass/index.scss
=> add spinner

src/partrials/modal.html, src/sass/components/_modal.scss
Перейменувала деякі класию Ні на що не впливає, окрім того, що менше кров з очей іде
=> fix class names

src/sass/base/_body.scss, src/sass/index.scss
Min-height, коли висота контенту 0, щоб футер не прилипав до хедера
=> Body min-height styles

src/index.html, src/index.js, src/js/modal.js, src/partrials/modal.html, src/sass/components/_modal.scss
1.Сорри, был конфликт пока я стягивала коммиты,не запушив свою ветку, в index.js, поэтому там сдвинут один импорт
2. Вика должна проверить js
=> Add modal.js and some changes in modal.scss

src/js/pageInStorage.js, src/js/visitEvents.js
=> fix storage,test git

src/js/pageInStorage.js, src/js/pagination.js, src/js/visitEvents.js
импорт currentPage из пагинации
=> import and change pagination currentPage

src/js/modal.js, src/sass/components/_modal.scss
=> Add running numbers

src/js/fetchMovies.js, src/partrials/header-library.html, src/partrials/header.html, src/sass/base/_base-components.scss, src/sass/components/_header-library.scss, src/sass/components/_header.scss
Поправил высоту хедера и вынес стили.
=> fix header and  Event button

src/js/cardListWithGenres.js, src/js/libFunc.js, src/js/loadPage.js, src/js/renderLibMovie.js, src/js/visitEvents.js, src/library.js
=> renderWithGenres

src/js/cardListWithGenres.js, src/js/renderLibMovie.js
=> first load fix, cross genres fix

src/js/fetchMovies.js, src/js/loadPage.js, src/js/modalFooter.js, src/js/storageKeys.js, src/js/visitEvents.js
Срабатывание окна возврата после завершения сессии, добавление текста в инпут
=> visitEvent after close

src/js/pagination.js, src/sass/base/_base-components.scss
=> display-block-current

src/js/modalFooter.js, src/partrials/footer.html, src/partrials/modalvm.html, src/sass/components/_mpdal_vm.scss
Пофіксила JS модалки. Зі стилями ще попрацюю.
=> Fixed modal close problem

src/js/fetchMovies.js, src/js/pagination.js
=> currentPage in FetchMovies

src/js/cardListWithGenres.js, src/js/fetchMovies.js, src/js/loadPage.js, src/js/modal.js, src/js/movieCard.js
add img placeholder to modal and handle the undefined or null response data
=> fix undefined/null response data

src/js/visitEvents.js
=> fixstorageLastSearchText

src/js/fetchMovies.js
=> fix movieName in search

src/index.html, src/js/arrowUp.js, src/js/loadPage.js, src/partrials/main.html, src/sass/components/_button.scss
=> Top button

src/partrials/header.html, src/sass/base/_base-components.scss
=> autocast logo

src/sass/base/_base-components.scss
=> logo transparent

src/sass/base/_base-components.scss
=> active logo

src/js/renderLibMovie.js, src/partrials/main-library.html, src/sass/base/_library-container.scss, src/sass/components/_pangation.scss, src/sass/components/_theme.scss
fixing colors pagination theme
=> pagination
